routes/admin.php
<?php


Route::group(['middleware' => 'web'], function() {
    
    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('unverifed_users','AdminController@unverified_users_index')->name('unverified_users.index');

        Route::get('users/document_verify_status', 'AdminController@document_verify_status')->name('users.document_verify_status');

        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::get('razorpay', 'AdminController@razorpay_settings_control')->name('razorpay_settings_control');

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // Documents CRUD operations

        Route::get('/kyc_documents/index', 'AdminController@kyc_documents_index')->name('kyc_documents.index');

        Route::get('/kyc_documents/create', 'AdminController@kyc_documents_create')->name('kyc_documents.create');

        Route::get('/kyc_documents/edit', 'AdminController@kyc_documents_edit')->name('kyc_documents.edit');

        Route::post('/kyc_documents/save', 'AdminController@kyc_documents_save')->name('kyc_documents.save');

        Route::get('/kyc_documents/view', 'AdminController@kyc_documents_view')->name('kyc_documents.view');

        Route::get('/kyc_documents/delete', 'AdminController@kyc_documents_delete')->name('kyc_documents.delete');

        Route::get('/kyc_documents/status', 'AdminController@kyc_documents_status')->name('kyc_documents.status');


        Route::get('wallets','AdminController@user_wallets_index')->name('user_wallets.index');

        Route::get('wallets/view','AdminController@user_wallets_view')->name('user_wallets.view');

        Route::get('wallets/payments','AdminController@user_wallet_payments')->name('user_wallet_payments.index');

        Route::get('wallets/payments/view','AdminController@user_wallet_payments_view')->name('user_wallet_payments.view');

        Route::get('wallets/payments/status','AdminController@user_wallet_payments_status')->name('user_wallet_payments.status');

        
        Route::get('user/documents/view/','AdminController@user_kyc_documents_view')->name('user_kyc_documents.view');

        Route::get('user/documents/view/','AdminController@user_kyc_documents_view')->name('user_kyc_documents.view');

        Route::get('generated_invoices','AdminController@generated_invoices_index')->name('generated_invoices.index');

        Route::get('generated_invoices/view', 'AdminController@generated_invoices_view')->name('generated_invoices.view');

        Route::get('generated_invoices/delete', 'AdminController@generated_invoices_delete')->name('generated_invoices.delete');

        Route::get('billing_accounts', 'AdminController@user_billing_accounts_index')->name('user_billing_accounts.index');

        Route::get('billing_accounts/create', 'AdminController@user_billing_accounts_create')->name('user_billing_accounts.create');


        Route::post('billing_accounts/save', 'AdminController@user_billing_accounts_save')->name('user_billing_accounts.save');

        Route::get('billing_accounts/view', 'AdminController@user_billing_accounts_view')->name('user_billing_accounts.view');

        Route::get('billing_accounts/edit', 'AdminController@user_billing_accounts_edit')->name('user_billing_accounts.edit');

        Route::get('billing_accounts/delete', 'AdminController@user_billing_accounts_delete')->name('user_billing_accounts.delete');

        Route::get('billing_accounts/status', 'AdminController@user_billing_accounts_status')->name('user_billing_accounts.status');

        Route::get('withdraw-requests','AdminController@user_withdrawals_index')->name('user_withdrawals.index');

        Route::get('withdraw-requests/view','AdminController@user_withdrawals_view')->name('user_withdrawals.view');

        Route::get('withdraw-requests/paynow', 'AdminController@user_withdrawals_paynow')->name('user_withdrawals.paynow');

        Route::get('withdraw-requests/decline', 'AdminController@user_withdrawals_decline')->name('user_withdrawals.decline');
        
        Route::get('resolution-center', 'AdminController@resolution_center_index')->name('resolution_center_index');

        Route::get('user_disputes', 'AdminController@user_disputes_index')->name('user_disputes.index');

        Route::get('user_disputes/view', 'AdminController@user_disputes_view')->name('user_disputes.view');

        Route::get('user_disputes/approve', 'AdminController@user_disputes_approve')->name('user_disputes.approve');

        Route::get('user_disputes/reject', 'AdminController@user_disputes_reject')->name('user_disputes.reject');

        Route::post('user_disputes/view', 'AdminController@user_disputes_message_save')->name('user_disputes.message_save');

        Route::post('inboxes/view', 'AdminController@inboxes_view')->name('inboxes.view');

       
        Route::post('/users/bulk_action', 'AdminController@users_bulk_action')->name('users.bulk_action');


    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

app/StaticPage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StaticPage extends Model
{
    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query->select('static_pages.*', 'static_pages.id as static_page_id', 'static_pages.unique_id as static_page_unique_id');
    
    }
}

resources/views/admin/static-pages/_form.blade.php
<div class="card-body">

    @if(Setting::get('is_demo_control_enabled') == NO )

        <form id="pages-form" class="forms-sample" action="{{ route('admin.static_pages.save') }}" method="POST" enctype="multipart/form-data" role="form">

    @else

        <form id="pages-form" class="forms-sample" role="form" enctype="multipart/form-data" role="form">

    @endif 

        @csrf

        <div class="form-body">

            <h3 class="card-title">{{tr('static_page_info')}}</h3>

            <hr>

            @if($static_page_details->id)

                <input type="hidden" name="static_page_id" value="{{$static_page_details->id}}">

            @endif

            <div class="row">

                <div class="form-group col-md-6">
                    
                    <label for="title">{{tr('title')}}<span class="admin-required">*</span> </label>
                    <input type="text" id="title" name="title" class="form-control" placeholder="Enter {{tr('title')}}" value="{{old('title')?: $static_page_details->title}}" required>
                    
                </div>

                <div class="form-group col-md-6">

                    <label for="page">
                        {{tr('select_static_page_type')}}
                        <span class="required" aria-required="true"> <span class="admin-required">*</span> </span>
                    </label>
                    
                    <select class="form-control select2" name="type" required>
                        <option value="">{{tr('select_static_page_type')}}</option>

                        @foreach($static_keys as $value)

                            <option value="{{$value}}" @if($value == $static_page_details->type) selected="true" @endif>{{ $value }}</option>

                        @endforeach 
                    </select>
                    
                </div>

                <div class="form-group col-md-12">

                    <label for="title">{{tr('description')}}<span class="admin-required">*</span></label>
                    
                    
                    <textarea style="display: none" id="description" name="description"></textarea>

                    <div id="code-editor" contenteditable="true">{!! old('description') ?:$static_page_details->description !!}</div>
                </div>

        </div> 


        <div class="form-actions top_form_action">

            <a  class="btn reset-btn btn-pill" href="{{route('admin.static_pages.index')}}">{{tr('reset')}}</a>

            @if(Setting::get('is_demo_control_enabled') == NO )

                <button type="submit" class="btn btn-primary btn-pill mr-2 pull-right">  <i class="fa fa-check"></i>{{ tr('save') }} </button>

            @else

                <button type="button" class="btn btn-primary btn-pill mr-2 pull-right" disabled> <i class="fa fa-check"></i>{{ tr('save') }}</button>
                
            @endif

        </div>

    </form>

</div>

<script>

var quill = new Quill('#code-editor', {
    theme: 'snow',
    modules: { toolbar: true },
});

$("#pages-form").submit(function() {

    var myEditor = document.querySelector('#code-editor');

    var html = myEditor.children[0].innerHTML;

    $("#description").val(html);

});

</script>

resources/views/admin/static-pages/_search.blade.php
<div class="col-md-12 mb-2">

        <form class="col-sm-12 col-sm-offset-6 search_box_css" action="{{route('admin.static_pages.index')}}" method="GET" role="search">

            <div class="row input-group">
                <div class="col-md-4"></div>
                <div class="col-md-3">
                    <input type="text" class="form-control" name="search_key" placeholder="{{tr('pages_search_placeholder')}}" value="{{Request::get('search_key')??''}}"> <span class="input-group-btn"></span>
                </div>

                <div class="col-md-2">

                    <select class="form-control" name="status">

                        <option value="">{{tr('select_status')}}</option>
                        <option value="{{APPROVED}}" @if(Request::get('status')== APPROVED && Request::get('status')!='') selected @endif>{{tr('approved')}}</option>
                        <option value="{{DECLINED}}" @if(Request::get('status')== DECLINED && Request::get('status')!='') selected @endif>{{tr('pending')}}</option>
                       
                    </select>
                </div>

                <button type="submit" class="btn btn-info">
                    <span class="glyphicon glyphicon-search"> {{tr('search')}}</span>
                </button> &nbsp;&nbsp;
                
                <a class="btn btn-danger" href="{{route('admin.static_pages.index')}}">{{tr('clear')}}</a>
            </div>

        </form>
</div>

resources/views/admin/static-pages/create.blade.php
@extends('layouts.admin')

@section('page_header', tr('static_pages'))

@section('breadcrumbs')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.static_pages.index') }}">{{tr('static_pages')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('add_static_page')}}</span>
    </li>
           
@endsection 

@section('content')
    
<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('add_static_page')}}

            <a class="btn btn-white pull-right" href="{{route('admin.static_pages.index')}}">

                <i class="fa fa-plus"></i> {{tr('view_static_pages')}}
            </a>
        </h4>

    </div>

    @include('admin.static-pages._form')

</div>

@endsection

resources/views/admin/static-pages/edit.blade.php
@extends('layouts.admin')

@section('title', tr('static_pages'))

@section('breadcrumbs')

    <li class="breadcrumb-item"><a href="{{ route('admin.static_pages.index') }}">{{tr('static_pages')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('edit_static_page') }}</span>
    </li>
           
@endsection 

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('edit_static_page')}}

            <a class="btn btn-white pull-right" href="{{route('admin.static_pages.index')}}">

                <i class="fa fa-plus"></i> {{tr('view_static_pages')}}
            </a>
        </h4>

    </div>

    @include('admin.static-pages._form')

</div>

@endsection

resources/views/admin/static-pages/index.blade.php
@extends('layouts.admin') 

@section('page_header', tr('static_pages'))

@section('breadcrumbs')

    <li class="breadcrumb-item"><a href="{{ route('admin.static_pages.index' )}}">{{tr('static_pages')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('view_static_pages') }}</span>
    </li>
           
@endsection 

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('view_static_pages')}}

            <button type="button" class="badge badge-square badge-outline-light" data-toggle="popover" data-content="{{tr('pages_note')}}">?</button>

            <a class="btn btn-white pull-right" href="{{route('admin.static_pages.create')}}">

                <i class="fa fa-plus"></i> {{tr('add_static_page')}}
            </a>
        </h4>

    </div>

    <div class="card-body">

         @include('admin.static-pages._search')
        <div class="table-responsive">


                <table id="dataTable" class="table data-table">

                    <thead>

                        <tr>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('title')}}</th>
                            <th>{{tr('static_page_type')}}</th>
                            <th>{{tr('status')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                        
                    </thead>

                    <tbody>

                        @foreach($static_pages as $i => $static_page_details)

                            <tr>
                                <td>{{$i+$static_pages->firstItem()}}</td>

                                <td>
                                    <a href="{{route('admin.static_pages.view' , ['static_page_id'=> $static_page_details->id] )}}"> {{$static_page_details->title}}</a>
                                </td>

                                <td class="text-capitalize">{{$static_page_details->type}}</td>

                                <td>
                                    @if($static_page_details->status == APPROVED)

                                      <span class="badge badge-success">{{tr('approved')}}</span> 

                                    @else

                                      <span class="badge badge-warning">{{tr('pending')}}</span> 
                                    @endif
                                </td>

                                <td>   
                                    <div class="dropdown">

                                        <button class="btn btn-outline-primary  dropdown-toggle btn-sm" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{tr('action')}}
                                        </button>

                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">

                                            <a class="dropdown-item" href="{{ route('admin.static_pages.view', ['static_page_id' => $static_page_details->id] ) }}">
                                                {{tr('view')}}
                                            </a>

                                            @if(Setting::get('is_demo_control_enabled') == NO)
                                            
                                                <a class="dropdown-item" href="{{ route('admin.static_pages.edit', ['static_page_id' => $static_page_details->id] ) }}">
                                                    {{tr('edit')}}
                                                </a>

                                                <a class="dropdown-item" 
                                                onclick="return confirm(&quot;{{tr('static_page_delete_confirmation' , $static_page_details->title)}}&quot;);" href="{{ route('admin.static_pages.delete', ['static_page_id' => $static_page_details->id] ) }}" >
                                                    {{ tr('delete') }}
                                                </a>

                                            @else

                                                <a class="dropdown-item" href="javascript:;">{{tr('edit')}}</a>

                                                <a class="dropdown-item" href="javascript:;">{{ tr('delete') }}</a>

                                            @endif

                                            <div class="dropdown-divider"></div>

                                            @if($static_page_details->status == APPROVED)

                                                <a class="dropdown-item" href="{{ route('admin.static_pages.status', ['static_page_id' =>  $static_page_details->id] ) }}" 
                                                onclick="return confirm(&quot;{{$static_page_details->title}} - {{tr('static_page_decline_confirmation')}}&quot;);"> 
                                                    {{tr('decline')}}
                                                </a>

                                            @else

                                                <a class="dropdown-item" href="{{ route('admin.static_pages.status', ['static_page_id' =>  $static_page_details->id] ) }}">
                                                    {{tr('approve')}}
                                                </a>
                                                   
                                            @endif

                                        </div>
                                         
                                    </div>
                                
                                </td>
                            
                            </tr>

                        @endforeach

                    </tbody>

                </table>


                <div class="pull-right">{{ $static_pages->appends(request()->input())->links() }}</div>

           

        </div>

    </div>

</div>

@endsection

resources/views/admin/static-pages/view.blade.php
@extends('layouts.admin') 

@section('page_header', tr('static_pages'))

@section('breadcrumbs')

    <li class="breadcrumb-item"><a href="{{route('admin.static_pages.index')}}">{{tr('static_pages')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{tr('view_static_pages')}}</span>
    </li>
           
@endsection  

@section('content')

<div class="card">
    
    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('view_static_pages')}}

        </h4>

    </div>

    <div class="card-group">

        <div class="card mb-4">

            <div class="card-body">

                <div class="custom-card">
                
                    <h5 class="card-title">{{tr('title')}}</h5>
                    
                    <p class="card-text">{{$static_page_details->title}}</p>

                </div> 

                <div class="custom-card">
                
                    <h5 class="card-title">{{tr('type')}}</h5>
                    
                    <p class="card-text">{{$static_page_details->type}}</p>

                </div>

                <div class="custom-card">
                
                    <h5 class="card-title">{{tr('status')}}</h5>
                    
                    <p class="card-text">

                        @if($static_page_details->status == APPROVED)

                            <span class="badge badge-success badge-md text-uppercase">{{tr('approved')}}</span>

                        @else 

                            <span class="badge badge-danger badge-md text-uppercase">{{tr('pending')}}</span>

                        @endif
                    
                    </p>

                </div>


                <div class="custom-card">
                
                <h5 class="card-title">{{tr('created_at')}}</h5>
                
                <p class="card-text">{{ common_date($static_page_details->created_at, Auth::guard('admin')->user()->timezone) }}</p>

            </div> 
                                        
                <div class="custom-card">
                
                    <h5 class="card-title">{{tr('updated_at')}}</h5>
                    
                    <p class="card-text">{{ common_date($static_page_details->updated_at, Auth::guard('admin')->user()->timezone) }}</p>

                </div>

               

                <hr>

                <div class="custom-card">
                
                    <div class="row">
                            
                        @if(Setting::get('is_demo_control_enabled') == NO)
                            <div class="col-md-4 col-lg-4">

                                <a href="{{ route('admin.static_pages.edit', ['static_page_id'=> $static_page_details->id] ) }}" class="btn btn-primary btn-block">{{tr('edit')}}</a>
                                
                            </div>                              

                            <div class="col-md-4 col-lg-4">
                                <a onclick="return confirm(&quot;{{tr('static_page_delete_confirmation' , $static_page_details->title)}}&quot;);" href="{{ route('admin.static_pages.delete', ['static_page_id'=> $static_page_details->id] ) }}" class="btn btn-danger btn-block">
                                    {{ tr('delete') }}
                                </a>

                            </div>                               

                        @else
                        
                            <div class="col-md-4 col-lg-4">
                                
                                <button class="btn btn-primary btn-block" disabled>{{ tr('edit') }}</button>

                            </div>
                            
                            <div class="col-md-4 col-lg-4">
                                
                                <button class="btn btn-warning btn-block" disabled>{{ tr('delete') }}</button>
                            </div>
                            
                        @endif

                        @if($static_page_details->status == APPROVED)

                            <div class="col-md-4 col-lg-4">
                                
                                <a class="btn btn-warning btn-block" href="{{ route('admin.static_pages.status', ['static_page_id'=> $static_page_details->id] ) }}" onclick="return confirm(&quot;{{ $static_page_details->title }}-{{tr('static_page_decline_confirmation' , $static_page_details->title)}}&quot;);">

                                    {{tr('decline')}}
                                </a>
                            </div>

                        @else

                            <div class="col-md-4 col-lg-4">
                                 <a class="btn btn-success btn-block" href="{{ route('admin.static_pages.status', ['static_page_id'=> $static_page_details->id] ) }}">
                                    {{tr('approve')}}
                                </a>
                            </div>
                               
                        @endif

                    </div>

                </div>

            </div>

        </div>

        <div class="card mb-4">

            <div class="card-body">

                <h4 class="card-title text-word-wrap">{{ tr('description') }}</h4>

                <p class="card-text">{!! $static_page_details->description !!}</p>
                
            </div>

        </div>

    </div>

</div>

@endsection