routes/admin.php
<?php


Route::group(['middleware' => 'web'], function() {
    
    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('unverifed_users','AdminController@unverified_users_index')->name('unverified_users.index');

        Route::get('users/document_verify_status', 'AdminController@document_verify_status')->name('users.document_verify_status');

        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::get('razorpay', 'AdminController@razorpay_settings_control')->name('razorpay_settings_control');

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // Documents CRUD operations

        Route::get('/kyc_documents/index', 'AdminController@kyc_documents_index')->name('kyc_documents.index');

        Route::get('/kyc_documents/create', 'AdminController@kyc_documents_create')->name('kyc_documents.create');

        Route::get('/kyc_documents/edit', 'AdminController@kyc_documents_edit')->name('kyc_documents.edit');

        Route::post('/kyc_documents/save', 'AdminController@kyc_documents_save')->name('kyc_documents.save');

        Route::get('/kyc_documents/view', 'AdminController@kyc_documents_view')->name('kyc_documents.view');

        Route::get('/kyc_documents/delete', 'AdminController@kyc_documents_delete')->name('kyc_documents.delete');

        Route::get('/kyc_documents/status', 'AdminController@kyc_documents_status')->name('kyc_documents.status');


        Route::get('wallets','AdminController@user_wallets_index')->name('user_wallets.index');

        Route::get('wallets/view','AdminController@user_wallets_view')->name('user_wallets.view');

        Route::get('wallets/payments','AdminController@user_wallet_payments')->name('user_wallet_payments.index');

        Route::get('wallets/payments/view','AdminController@user_wallet_payments_view')->name('user_wallet_payments.view');

        Route::get('wallets/payments/status','AdminController@user_wallet_payments_status')->name('user_wallet_payments.status');

        
        Route::get('user/documents/view/','AdminController@user_kyc_documents_view')->name('user_kyc_documents.view');

        Route::get('user/documents/view/','AdminController@user_kyc_documents_view')->name('user_kyc_documents.view');

        Route::get('generated_invoices','AdminController@generated_invoices_index')->name('generated_invoices.index');

        Route::get('generated_invoices/view', 'AdminController@generated_invoices_view')->name('generated_invoices.view');

        Route::get('generated_invoices/delete', 'AdminController@generated_invoices_delete')->name('generated_invoices.delete');

        Route::get('billing_accounts', 'AdminController@user_billing_accounts_index')->name('user_billing_accounts.index');

        Route::get('billing_accounts/create', 'AdminController@user_billing_accounts_create')->name('user_billing_accounts.create');


        Route::post('billing_accounts/save', 'AdminController@user_billing_accounts_save')->name('user_billing_accounts.save');

        Route::get('billing_accounts/view', 'AdminController@user_billing_accounts_view')->name('user_billing_accounts.view');

        Route::get('billing_accounts/edit', 'AdminController@user_billing_accounts_edit')->name('user_billing_accounts.edit');

        Route::get('billing_accounts/delete', 'AdminController@user_billing_accounts_delete')->name('user_billing_accounts.delete');

        Route::get('billing_accounts/status', 'AdminController@user_billing_accounts_status')->name('user_billing_accounts.status');

        Route::get('withdraw-requests','AdminController@user_withdrawals_index')->name('user_withdrawals.index');

        Route::get('withdraw-requests/view','AdminController@user_withdrawals_view')->name('user_withdrawals.view');

        Route::get('withdraw-requests/paynow', 'AdminController@user_withdrawals_paynow')->name('user_withdrawals.paynow');

        Route::get('withdraw-requests/decline', 'AdminController@user_withdrawals_decline')->name('user_withdrawals.decline');
        
        Route::get('resolution-center', 'AdminController@resolution_center_index')->name('resolution_center_index');

        Route::get('user_disputes', 'AdminController@user_disputes_index')->name('user_disputes.index');

        Route::get('user_disputes/view', 'AdminController@user_disputes_view')->name('user_disputes.view');

        Route::get('user_disputes/approve', 'AdminController@user_disputes_approve')->name('user_disputes.approve');

        Route::get('user_disputes/reject', 'AdminController@user_disputes_reject')->name('user_disputes.reject');

        Route::post('user_disputes/view', 'AdminController@user_disputes_message_save')->name('user_disputes.message_save');

        Route::post('inboxes/view', 'AdminController@inboxes_view')->name('inboxes.view');

       
        Route::post('/users/bulk_action', 'AdminController@users_bulk_action')->name('users.bulk_action');


    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Setting, DB;

class User extends Authenticatable
{

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $appends = ['is_notification'];

    public function getIsNotificationAttribute() {

        return $this->email_notification_status;
    }

    /**
     * Get the UserCard record associated with the user.
     */
    public function userCards() {
        
        return $this->hasMany(UserCard::class, 'user_id');
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        return $query->where('users.is_kyc_document_approved', USER_KYC_DOCUMENT_APPROVED)->where('users.status', USER_APPROVED)->where('users.is_verified', USER_EMAIL_VERIFIED);
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query->select(
            'users.id as user_id',
            'users.unique_id as user_unique_id',
            'users.*'
            );
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOtherResponse($query) {

        return $query->select(
            'users.id as user_id',
            'users.unique_id as user_unique_id',
            'users.username',
            'users.name',
            'users.email',
            'users.picture',
            'users.mobile',
            'users.created_at',
            'users.updated_at'
            );
    
    }
    
    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['name'] = $model->attributes['first_name']." ".$model->attributes['last_name'];

            
            if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                $model->generateEmailCode();            

            } else {
                
                $model->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            }

            $model->attributes['payment_mode'] = COD;

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = \Helper::generate_token();

            $model->attributes['token_expiry'] = \Helper::generate_token_expiry();

            $model->attributes['status'] = USER_APPROVED;

            if(in_array($model->attributes['login_by'], ['facebook', 'google', 'apple', 'linkedin', 'instagram'] )) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['username'] = routefreestring($model->attributes['name'].$model->attributes['id']);

            $model->attributes['unique_id'] = "UID"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = routefreestring($model->attributes['name']);

            $model->attributes['name'] = $model->attributes['first_name']." ".$model->attributes['last_name'];

        });

        static::deleting(function ($model){

            \Helper::delete_file($model->picture , PROFILE_PATH_USER);

        });

    }

    /**
     * Generates Token and Token Expiry
     * 
     * @return bool returns true if successful. false on failure.
     */

    protected function generateEmailCode() {

        $this->attributes['verification_code'] = \Helper::generate_email_code();

        $this->attributes['verification_code_expiry'] = \Helper::generate_email_expiry();

        // Check Email verification controls and email configurations

        if(Setting::get('is_account_email_verification') == YES && Setting::get('is_email_notification') == YES && Setting::get('is_email_configured') == YES) {
            
            if($this->attributes['login_by'] != 'manual') {
                
                $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            } else {
                
                $this->attributes['is_verified'] = USER_EMAIL_NOT_VERIFIED;
            }

        } else { 

            $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;
        }
        
        return true;
    
    }

}

resources/views/admin/users/billing_accounts/_form.blade.php
<div class="card-body">

    @if(Setting::get('is_demo_control_enabled') == NO )

    <form method="POST" action="{{route('admin.user_billing_accounts.save')}}" role="form">

        @else

        <form class="forms-sample" role="form">

            @endif

            @csrf

            <div class="form-body">


                <input type="hidden" name="user_id" value="{{Request::get('user_id')?? $user_details->user_id}}">


                <input type="hidden" name="billing_account_id" value="{{Request::get('billing_account_id')??''}}">

                <div class="row p-t-20">

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('nickname')}}<span class="admin-required">*</span></label>

                        <input type="text" name="nickname" value="{{old('nickname') ?: $user_details->nickname}}" class="form-control" placeholder="{{tr('nickname')}}" required>

                    </div>

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('account_holder_name')}}<span class="admin-required">*</span></label>
                        <input type="text" name="account_holder_name" value="{{old('account_holder_name') ?: $user_details->account_holder_name}}" class="form-control" placeholder="{{tr('account_holder_name')}}" required>

                    </div>


                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('account_no')}}<span class="admin-required">*</span></label>
                        <input type="number" min="1" step="any" class="form-control" name="account_number" value="{{old('account_number') ?:  $user_details->account_number}}" placeholder="867676576" required>

                    </div>

                    <div class="form-group col-md-6">

                        <label class="control-label">
                            {{tr('bank_name')}}<span class="admin-required">*</span>
                        </label>

                        <input type="text" class="form-control" name="bank_name" value="{{old('bank_name') ?:  $user_details->bank_name}}" placeholder="ABCD Bank" required>

                    </div>

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('ifsc_code')}}<span class="admin-required">*</span></label>
                        <input type="text" class="form-control" name="ifsc_code" value="{{old('ifsc_code') ?: $user_details->ifsc_code}}" placeholder="{{tr('ifsc_code')}}" required>

                    </div>

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('swift_code')}}<span class="admin-required">*</span></label>
                        <input type="text" class="form-control" name="swift_code" value="{{old('swift_code') ?: $user_details->swift_code}}" placeholder="{{tr('swift_code')}}" required>

                    </div>



                </div>



            </div>

            <div class="form-actions">

                @if(Setting::get('is_demo_control_enabled') == NO )

                <button type="submit" class="btn btn-primary btn-pill pull-right"> <i class="fa fa-check"></i>{{tr('save')}}</button>

                @else

                <button type="button" class="btn btn-primary btn-pill pull-right"> <i class="fa fa-check"></i>{{tr('save')}}</button>

                @endif

                <a  class="btn reset-btn btn-pill" href="{{route('admin.user_billing_accounts.index',['user_id'=> Request::get('user_id')?? $user_details->user_id])}}">{{tr('reset')}}</a>

            </div>

        </form>

</div>

resources/views/admin/users/billing_accounts/_search.blade.php
<div class="col-md-12 mb-2">

    <form class="col-sm-12 col-sm-offset-6 search_box_css" action="{{route('admin.user_billing_accounts.index')}}" method="GET" role="search">
        {{csrf_field()}}

        <div class="row input-group">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <input type="hidden" name="user_id" value="{{$user_details->id??''}}">
                <input type="text" class="form-control" name="search_key" placeholder="{{tr('billing_account_search_placeholder')}}" value="{{Request::get('search_key')??''}}">
            </div>

            <div class="col-md-3 flex">
                <span class="input-group-btn">
                    &nbsp; &nbsp;
                    <button type="submit" class="btn btn-info">
                        <span class="glyphicon glyphicon-search"> {{tr('search')}}</span>
                    </button>
                    <a class="btn btn-danger" href="{{route('admin.user_billing_accounts.index',['user_id'=>$user_details->id])}}">{{tr('clear')}}</a>
                </span>
            </div>
        </div>

    </form>

</div>

resources/views/admin/users/billing_accounts/create.blade.php
@extends('layouts.admin')

@section('page_header',tr('users'))

@section('styles')

<link rel="stylesheet" href="{{asset('admin-assets/css/dropify.min.css')}}">

<link href="{{asset('admin-assets/css/datepicker.css')}}" rel="stylesheet">

@endsection

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.users.view')}}">{{tr('view_users')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)" aria-current="page"></a><span>{{tr('add_billing_accounts')}}</span></li>

@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">
            <a class="m-b-0 text-white" href="{{route('admin.users.index',['user_id'=> Request::get('user_id')?? $user_details->user_id])}}">{{tr('add_billing_accounts')}} - {{$user_details->username??''}} </a>

        
            <a class="btn btn-secondary pull-right" href="{{route('admin.user_billing_accounts.index',['user_id'=> Request::get('user_id')?? $user_details->user_id])}}">
                <i class="fa fa-eye"></i> {{tr('view_billing_accounts')}}
            </a>
        </h4>

    </div>

    @include('admin.users.billing_accounts._form')

</div>

@endsection

resources/views/admin/users/billing_accounts/edit.blade.php
@extends('layouts.admin')

@section('page_header',tr('users'))

@section('styles')

<link rel="stylesheet" href="{{asset('admin-assets/css/dropify.min.css')}}">

<link href="{{asset('admin-assets/css/datepicker.css')}}" rel="stylesheet">

@endsection

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.users.index')}}">{{tr('users')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)"></a> {{tr('edit_user')}}</li>

@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('edit_billing_account')}}</h4>

    </div>

    @include('admin.users.billing_accounts._form')

</div>

@endsection

resources/views/admin/users/billing_accounts/index.blade.php
@extends('layouts.admin')

@section('page_header',tr('users'))

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.users.index')}}">{{tr('view_users')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)"></a>{{tr('billing_accounts')}}</li>

@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">


        <h4 class="m-b-0 text-white"><a class="m-b-0 text-white" href="{{route('admin.users.view',['user_id'=>$user_details->id])}}">{{$user_details->name??''}}</a> - {{ tr('billing_accounts')}}

            <button type="button" class="badge badge-square badge-outline-light" data-toggle="popover" data-content="{{tr('billing_accounts_note')}}">?</button>

            <a class="btn btn-white pull-right" href="{{route('admin.user_billing_accounts.create',['user_id'=>$user_details->id])}}">
                <i class="fa fa-plus"></i> {{tr('add_billing_accounts')}}
            </a>
        </h4>

    </div>

    <div class="card-body">

        @include('admin.users.billing_accounts._search')

        <div class="table-responsive">


            <table id="dataTable" class="table data-table">

                <thead>
                    <tr>
                        <th>{{tr('s_no')}}</th>
                        <th>{{tr('account_holder_name')}}</th>
                        <th>{{tr('account_no')}}</th>
                        <th>{{tr('ifsc_code')}}</th>
                        <th>{{tr('swift_code')}}</th>
                        <th>{{tr('action')}}</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach($user_billing_accounts as $i => $account_details)

                    <tr>
                        <td>{{$i+$user_billing_accounts->firstItem()}}</td>

                        <td>
                            <a href="{{route('admin.user_billing_accounts.view',['billing_account_id'=>$account_details->id])}}"> {{$account_details->account_holder_name}}</a>
                        </td>

                        <td>
                            {{$account_details->account_number}}
                        </td>

                        <td>{{$account_details->ifsc_code}}</td>

                        <td>
                            {{$account_details->swift_code}}
                        </td>



                        <td >
                            <a class="btn btn-outline-info btn-sm" href="{{ route('admin.user_billing_accounts.edit', ['billing_account_id' => $account_details->id]) }}">
                                {{ tr('edit') }}
                            </a>&nbsp;

                            <a class="btn btn-outline-danger btn-sm" href="{{ route('admin.user_billing_accounts.delete', ['billing_account_id' => $account_details->id]) }}" onclick="return confirm(&quot;{{tr('account_delete_confirmation')}}&quot;);">
                                {{ tr('delete') }}
                            </a>

                        </td>



                    </tr>
                    @endforeach

                </tbody>

            </table>

            <div class="pull-right">{{ $user_billing_accounts->appends(request()->input())->links() }}</div>
        </div>

    </div>

</div>

@endsection

resources/views/admin/users/billing_accounts/view.blade.php
@extends('layouts.admin')

@section('page_header',tr('users'))

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.users.index')}}">{{tr('view_users')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)"></a>{{tr('view_billing_accounts')}}</li>
@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('view_billing_accounts')}}</h4>

    </div>

    <div class="card-body">

        <div class="row">

            <div class="col-6">

                <!-- Card content -->
                <div class="card-body">

                    <div class="template-demo">

                        <table class="table mb-0">

                            <thead>

                            </thead>

                            <tbody>

                                <tr>
                                    <td class="pl-0"><b>{{ tr('name') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div><a href="{{route('admin.users.view',['user_id'=>$user_account_details->user_id])}}">{{$user_account_details->user->name}}</a></div>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="pl-0"><b>{{ tr('nickname') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div>{{$user_account_details->nickname}}</div>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="pl-0"><b>{{ tr('account_holder_name') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div>{{$user_account_details->account_holder_name}}</div>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="pl-0"><b>{{ tr('account_no') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div>{{$user_account_details->account_number ?:tr('not_available')}}</div>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="pl-0"><b>{{ tr('bank_name') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div>{{$user_account_details->bank_name ?:tr('not_available')}}</div>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="pl-0"><b>{{ tr('ifsc_code') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div>{{$user_account_details->ifsc_code}}</div>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="pl-0"><b>{{ tr('swift_code') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div>{{$user_account_details->swift_code}}</div>
                                    </td>
                                </tr>



                                <tr>

                                    <td class="pl-0"> <b>{{ tr('status') }}</b></td>

                                    <td class="pr-0 text-right">

                                        @if($user_account_details->status == APPROVED)

                                              <span class="card-text badge badge-success badge-md text-uppercase">{{tr('approved')}}</span>

                                        @else

                                               <span class="card-text badge badge-danger badge-md text-uppercase">{{tr('declined')}}</span>

                                        @endif

                                    </td>

                                </tr>



                                <tr>
                                    <td class="pl-0"> <b>{{ tr('created_at') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div>{{ common_date($user_account_details->created_at, Auth::guard('admin')->user()->timezone,'d M Y H:i:s') }}</div>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="pl-0"> <b>{{ tr('updated_at') }}</b></td>
                                    <td class="pr-0 text-right">
                                        <div>{{ common_date($user_account_details->updated_at,Auth::guard('admin')->user()->timezone, 'd M Y H:i:s') }}</div>
                                    </td>
                                </tr>

                            </tbody>

                        </table>

                    </div>

                </div>

            </div>


            <div class="col-6">

                <br><br>

                <div class="row">

                    <div class="col-6">

                        @if(Setting::get('is_demo_control_enabled') == YES)

                        <a href="javascript:;" class="btn btn-primary btn-block">{{tr('edit')}}</a>

                        <a href="javascript:;" class="btn btn-danger btn-block">{{tr('delete')}}</a>

                        @else

                        <a class="btn btn-primary btn-block" href="{{ route('admin.user_billing_accounts.edit', ['billing_account_id' => $user_account_details->id])}}">{{tr('edit')}}</a>

                        <a class="btn btn-danger btn-block" href="{{route('admin.user_billing_accounts.delete', ['billing_account_id' => $user_account_details->id])}}" onclick="return confirm(&quot;{{tr('account_delete_confirmation' , $user_account_details->name)}}&quot;);">{{tr('delete')}}</a>

                        @endif

                    </div>



                </div>



            </div>

        </div>

    </div>

</div>

@endsection