routes/admin.php
<?php


Route::group(['middleware' => 'web'], function() {
    
    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('unverifed_users','AdminController@unverified_users_index')->name('unverified_users.index');

        Route::get('users/document_verify_status', 'AdminController@document_verify_status')->name('users.document_verify_status');

        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::get('razorpay', 'AdminController@razorpay_settings_control')->name('razorpay_settings_control');

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // Documents CRUD operations

        Route::get('/kyc_documents/index', 'AdminController@kyc_documents_index')->name('kyc_documents.index');

        Route::get('/kyc_documents/create', 'AdminController@kyc_documents_create')->name('kyc_documents.create');

        Route::get('/kyc_documents/edit', 'AdminController@kyc_documents_edit')->name('kyc_documents.edit');

        Route::post('/kyc_documents/save', 'AdminController@kyc_documents_save')->name('kyc_documents.save');

        Route::get('/kyc_documents/view', 'AdminController@kyc_documents_view')->name('kyc_documents.view');

        Route::get('/kyc_documents/delete', 'AdminController@kyc_documents_delete')->name('kyc_documents.delete');

        Route::get('/kyc_documents/status', 'AdminController@kyc_documents_status')->name('kyc_documents.status');


        Route::get('wallets','AdminController@user_wallets_index')->name('user_wallets.index');

        Route::get('wallets/view','AdminController@user_wallets_view')->name('user_wallets.view');

        Route::get('wallets/payments','AdminController@user_wallet_payments')->name('user_wallet_payments.index');

        Route::get('wallets/payments/view','AdminController@user_wallet_payments_view')->name('user_wallet_payments.view');

        Route::get('wallets/payments/status','AdminController@user_wallet_payments_status')->name('user_wallet_payments.status');

        
        Route::get('user/documents/view/','AdminController@user_kyc_documents_view')->name('user_kyc_documents.view');

        Route::get('user/documents/view/','AdminController@user_kyc_documents_view')->name('user_kyc_documents.view');

        Route::get('generated_invoices','AdminController@generated_invoices_index')->name('generated_invoices.index');

        Route::get('generated_invoices/view', 'AdminController@generated_invoices_view')->name('generated_invoices.view');

        Route::get('generated_invoices/delete', 'AdminController@generated_invoices_delete')->name('generated_invoices.delete');

        Route::get('billing_accounts', 'AdminController@user_billing_accounts_index')->name('user_billing_accounts.index');

        Route::get('billing_accounts/create', 'AdminController@user_billing_accounts_create')->name('user_billing_accounts.create');


        Route::post('billing_accounts/save', 'AdminController@user_billing_accounts_save')->name('user_billing_accounts.save');

        Route::get('billing_accounts/view', 'AdminController@user_billing_accounts_view')->name('user_billing_accounts.view');

        Route::get('billing_accounts/edit', 'AdminController@user_billing_accounts_edit')->name('user_billing_accounts.edit');

        Route::get('billing_accounts/delete', 'AdminController@user_billing_accounts_delete')->name('user_billing_accounts.delete');

        Route::get('billing_accounts/status', 'AdminController@user_billing_accounts_status')->name('user_billing_accounts.status');

        Route::get('withdraw-requests','AdminController@user_withdrawals_index')->name('user_withdrawals.index');

        Route::get('withdraw-requests/view','AdminController@user_withdrawals_view')->name('user_withdrawals.view');

        Route::get('withdraw-requests/paynow', 'AdminController@user_withdrawals_paynow')->name('user_withdrawals.paynow');

        Route::get('withdraw-requests/decline', 'AdminController@user_withdrawals_decline')->name('user_withdrawals.decline');
        
        Route::get('resolution-center', 'AdminController@resolution_center_index')->name('resolution_center_index');

        Route::get('user_disputes', 'AdminController@user_disputes_index')->name('user_disputes.index');

        Route::get('user_disputes/view', 'AdminController@user_disputes_view')->name('user_disputes.view');

        Route::get('user_disputes/approve', 'AdminController@user_disputes_approve')->name('user_disputes.approve');

        Route::get('user_disputes/reject', 'AdminController@user_disputes_reject')->name('user_disputes.reject');

        Route::post('user_disputes/view', 'AdminController@user_disputes_message_save')->name('user_disputes.message_save');

        Route::post('inboxes/view', 'AdminController@inboxes_view')->name('inboxes.view');

       
        Route::post('/users/bulk_action', 'AdminController@users_bulk_action')->name('users.bulk_action');


    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

resources/views/layouts/admin/_logout_model.blade.php
<div class="modal fade" id="logoutModel" tabindex="-1" role="dialog" aria-labelledby="logoutModel" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="logoutModelTitle">{{tr('confirm_logout')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <h5>{{tr('logout_note')}}</h5>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-pill" data-dismiss="modal">{{tr('close')}}</button>
                <a class="btn btn-primary btn-pill" href="{{route('admin.logout')}}">{{tr('logout')}}</a>
            </div>

        </div>

    </div>
    
</div>

resources/views/layouts/admin/focused.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
        <meta charset="utf-8" />
        <title>{{Setting::get('site_name')}}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
        <link rel="icon" type="image/x-icon" href="{{Setting::get('site_icon')}}" />

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-touch-fullscreen" content="yes" />

        <meta name="apple-mobile-web-app-status-bar-style" content="default" />

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

        <!-- Please remove the file below for production: Contains demo classes -->
        <link class="main-stylesheet" href="{{asset('admin-assets/css/style.css')}}" rel="stylesheet" type="text/css" />
     
        <link href="{{asset('admin-assets/plugins/toaster/toastr.min.css')}}" rel="stylesheet" />

     
        <style>
            .login-wrapper {
                background: url("{{asset('/images/login-bg.jpg')}}");
                background-size: contain;
                background-repeat: no-repeat;
                background-position: none;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }
        </style>

    </head>
    <body class="fixed-header menu-pin menu-behind">
        <div class="login-wrapper">
            <!-- START Login Background Pic Wrapper-->
            <div class="bg-pic">
                <!-- START Background Caption-->
                <div class="bg-caption pull-bottom sm-pull-bottom text-white p-l-20 m-b-20">
                </div>
                <!-- END Background Caption-->
            </div>
            <!-- END Login Background Pic Wrapper-->

            <!-- START Login Right Container-->

            @yield('content')
            <!-- END Login Right Container-->
            @include('layouts.admin.scripts')

            @include('notifications.notify')


        </div>
       

        <script src="{{asset('/admin-assets/js/jstz.min.js')}}"></script>

        <script>
            $(document).ready(function() {

                var dMin = new Date().getTimezoneOffset();
                var dtz = -(dMin/60);
                $("#admin-timezone").val(jstz.determine().name());
            });
        </script>
    </body>
</html>

resources/views/layouts/admin/footer.blade.php
<!-- START COPYRIGHT -->
<!-- START CONTAINER FLUID -->
<!-- START CONTAINER FLUID -->
<div class=" container-fluid  container-fixed-lg footer">
<div class="copyright sm-text-center">

<div class="clearfix"></div>
</div>
</div>
<!-- END COPYRIGHT -->

resources/views/layouts/admin/header.blade.php
<header class="main-header" id="header">

    <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
        
        <button id="sidebar-toggler" class="sidebar-toggle">
            <span class="sr-only">Toggle navigation</span>
        </button>


        <div class="navbar-right ">

           
           
            <ul class="nav navbar-nav">

                 <li class="nav-item d-none d-lg-block">
                <a class="btn btn-primary btn-fw" id="visit-website" href="{{Setting::get('frontend_url')}}" target="_blank">
                    Visit Website
                </a>
            </li>
              
                <li class="dropdown user-menu">

                    <button class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <img src="{{Auth::guard('admin')->user()->picture ?? '-'}}" class="user-image rounded-circle header-profile-image" />
                        <span class="d-none d-lg-inline-block">{{Auth::guard('admin')->user()->name ?? '-'}}</span>
                    </button>

                    <ul class="dropdown-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-link-item" href="{{route('admin.profile')}}">
                                <i class="mdi mdi-account-outline"></i>
                                <span class="nav-text">{{tr('my_profile')}}</span>
                            </a>
                        </li>

                        <li class="dropdown-footer">
                            <a class="dropdown-link-item"  data-toggle="modal" data-target="#logoutModel" style="cursor:pointer"> <i class="mdi mdi-logout pull-left"></i> {{tr('logout')}}</a>
                        </li>
                    </ul>

                </li>

            </ul>

        </div>

    </nav>

</header>

resources/views/layouts/admin/scripts.blade.php
<script src="{{asset('admin-assets/plugins/jquery/jquery.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/simplebar/simplebar.min.js')}}"></script>

<script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>

<script src="{{asset('admin-assets/plugins/apexcharts/apexcharts.js')}}"></script>

<script src="{{asset('admin-assets/plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/jvectormap/jquery-jvectormap-world-mill.js')}}"></script>

<script src="{{asset('admin-assets/plugins/nprogress/nprogress.js')}}"></script>

<script src="{{asset('admin-assets/plugins/jvectormap/jquery-jvectormap-us-aea.js')}}"></script>

<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<script src="{{asset('admin-assets/plugins/toaster/toastr.min.js')}}"></script>

<script src="{{asset('admin-assets/js/mono.js')}}"></script>

<script src="{{asset('admin-assets/js/chart.js')}}"></script>

<script src="{{asset('admin-assets/js/map.js')}}"></script>

<script src="{{asset('admin-assets/js/select2.min.js')}}"></script>

<script src="{{asset('admin-assets/js/custom.js')}}"></script>


<script src="{{asset('admin-assets/plugins/daterangepicker/moment.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/daterangepicker/daterangepicker.js')}}"></script>

<!-- <script src="http://cdn.ckeditor.com/4.5.5/standard/ckeditor.js"></script> -->
<script>
    $(document).ready(function() {

    	// if($('.ckeditor').length) {
    	// 	CKEDITOR.replace('ckeditor');
    	// }
        
        $('.select2').select2();
        
        var dataTable = $('#dataTable');
		 
		if (dataTable.length != 0){

		    dataTable.DataTable({
            	info: false,
	            "lengthMenu": [[5, 10, 15, -1], [5, 10, 15, "All"]],
				"pageLength":10,
				"lengthChange": false,
				'sDom': 'lrtip',
		    });
		}

		$('#dataTable_paginate').hide();
    
    });


	
</script>

resources/views/layouts/admin/sidebar.blade.php
<aside class="left-sidebar sidebar-dark" id="left-sidebar">

    <div id="sidebar" class="sidebar sidebar-with-footer">
        <!-- Aplication Brand -->
        <div class="app-brand">
            <a href="{{route('admin.dashboard')}}">
                <!-- <img src="{{Setting::get('site_logo')}}" alt="{{Setting::get('site_name')}}" class="logo"> -->
                <span class="brand-name text-uppercase">{{Setting::get('site_name')}}</span>
            </a>
        </div>
        <!-- begin sidebar scrollbar -->
        <div class="sidebar-left" data-simplebar style="height: 100%;">
            <!-- sidebar menu -->
            <ul class="nav sidebar-inner" id="sidebar-menu">

                <li class="has-sub" id="dashboard">
                    <a class="sidenav-item-link" href="{{route('admin.dashboard')}}">
                        <i class="mdi mdi-briefcase-account-outline"></i>
                        <span class="nav-text">{{tr('dashboard')}}</span>
                    </a>
                </li>

                <!-- account_management start -->

                <li class="section-title">{{tr('account_management')}}</li>

                <li class="has-sub" id="users_crud">

                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#users" aria-expanded="false" aria-controls="users">
                        <i class="mdi mdi-account-multiple"></i>
                        <span class="nav-text">{{tr('users')}}</span> <b class="caret"></b>
                    </a>
                    <ul class="collapse" id="users" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <li id="users-create">
                                <a class="sidenav-item-link" href="{{route('admin.users.create')}}">
                                    <span class="nav-text">{{tr('add_user')}}</span>

                                </a>
                            </li>

                            <li id="users-index">
                                <a class="sidenav-item-link" href="{{route('admin.users.index')}}">
                                    <span class="nav-text">{{tr('view_users')}}</span>

                                </a>
                            </li>

                        </div>
                    </ul>

                </li>

                <li id="user_unverified">
                    <a class="sidenav-item-link" href="{{route('admin.unverified_users.index')}}">
                        <i class="mdi mdi-arrange-send-to-back"></i>
                        <span class="nav-text">Unverified Users</span>
                    </a>
                </li>

                <!-- account_management end -->

                <li class="section-title"><span class="title">{{tr('wallet_management')}}</span></li>

                <li class="has-sub" id="wallets_management">
                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#user_wallets" aria-expanded="true" aria-controls="user_wallets">
                        <i class="mdi mdi-wallet"></i>
                        <span class="nav-text">{{tr('wallets')}}</span> <b class="caret"></b>
                    </a>
                    <ul class="collapse" id="user_wallets" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <li id="user_wallets-index">
                                <a class="sidenav-item-link" href="{{route('admin.user_wallets.index')}}">
                                    <i class="fa fa-circle-o"></i>{{tr('user_wallets')}}
                                </a>
                            </li>

                            <li id="user_wallets-transactions" class="">
                                <a class="sidenav-item-link" href="{{route('admin.user_wallet_payments.index')}}">
                                    <i class="fa fa-circle-o"></i>{{tr('transactions')}}
                                </a>
                            </li>

                            <li id="bank_transactions" class="">
                                <a class="sidenav-item-link" href="{{route('admin.user_wallet_payments.index',['type'=>BANK_TRANSFER])}}">
                                    <i class="fa fa-circle-o"></i>{{tr('bank_transactions')}}
                                </a>
                            </li>

                        </div>
                    </ul>

                </li>

                <li class="has-sub" id="invoices_management">

                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#invoices" aria-expanded="true" aria-controls="invoices">
                        <i class="mdi mdi-cash-multiple"></i>
                        <span class="nav-text">{{tr('invoices')}}</span> <b class="caret"></b>
                    </a>
                    <ul class="collapse" id="invoices" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <!-- <li id="invoices-user">
                                <a href="#">
                                    <i class="fa fa-circle-o"></i>Create Invoice
                                </a>
                            </li> -->

                            <li id="invoices-view">
                                <a class="sidenav-item-link" href="{{route('admin.generated_invoices.index')}}">
                                    <i class="fa fa-circle-o"></i>{{tr('view_invoices')}}
                                </a>
                            </li>

                            <li id="invoices-pending">
                                <a class="sidenav-item-link" href="{{route('admin.generated_invoices.index',['pending_invoices'=>YES])}}">
                                    <i class="fa fa-circle-o"></i>{{tr('pending_invoices')}}
                                </a>
                            </li>

                        </div>
                    </ul>

                </li>

                <li class="has-sub" id="resolution_center_management" style="display: none;">

                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#resolution_center" aria-expanded="true" aria-controls="resolution_center">
                        <i class="mdi mdi-flag"></i>
                        <span class="nav-text">{{tr('resolution_center')}}</span> <b class="caret"></b>
                    </a>
                    <ul class="collapse" id="resolution_center" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <li id="resolution-center-all">
                                <a class="sidenav-item-link" href="{{route('admin.resolution_center_index')}}">
                                    <i class="fa fa-circle-o"></i> {{tr('all_cases')}}
                                </a>
                            </li>

                            <li id="resolution-center-opened">
                                <a class="sidenav-item-link" href="{{route('admin.resolution_center_index',['type'=>NO])}}">
                                    <i class="fa fa-circle-o"></i>{{tr('opened_cases')}}
                                </a>
                            </li>

                            <li id="resolution-center-closed">
                                <a class="sidenav-item-link" href="{{route('admin.resolution_center_index',['type'=>YES])}}">
                                    <i class="fa fa-circle-o"></i>{{tr('closed_cases')}}
                                </a>
                            </li>

                        </div>
                    </ul>

                </li>

                <!-- <li id="resolution-center">
                    <a class="sidenav-item-link" href="{{route('admin.resolution_center_index')}}">
                        <i class="mdi mdi-flag"></i>
                        <span class="nav-text">{{tr('resolution_center')}}</span>
                    </a>
                </li> -->

                <li id="withdrawals_list">
                    <a class="sidenav-item-link" href="{{route('admin.user_withdrawals.index')}}">
                        <!-- <i class="mdi mdi-cannabis"></i> -->
                        <img src="{{asset('images/atm.svg')}}" width="25" height="25" />
                        <span class="nav-text break_word_css">{{tr('withdraw_requests')}}</span>
                    </a>
                </li>

                <li id="user_disputes">
                    <a class="sidenav-item-link" href="{{route('admin.user_disputes.index')}}">
                        <i class="mdi mdi-bullhorn"></i>
                        <span class="nav-text">{{tr('disputes')}}</span>
                    </a>
                </li>

                <li class="section-title">
                    <span class="title">Lookup Management</span>
                </li>

                <li class="has-sub" id="lookup_management">

                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#lookup_management_documents" aria-expanded="false" aria-controls="users">
                        <i class="mdi mdi-file-hidden"></i>
                        <span class="nav-text">Documents</span> <b class="caret"></b>
                    </a>

                    <ul class="collapse" id="lookup_management_documents" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <li id="kyc_documents_create">
                                <a class="sidenav-item-link" href="{{route('admin.kyc_documents.create')}}">
                                    <span class="nav-text">Add Documents</span>

                                </a>
                            </li>

                            <li id="kyc_documents_index">
                                <a class="sidenav-item-link" href="{{route('admin.kyc_documents.index')}}">
                                    <span class="nav-text">View Documents</span>

                                </a>
                            </li>

                            <!-- <li id="users-index">
                                <a class="sidenav-item-link" href="{{route('admin.kyc_documents.index')}}">
                                    <span class="nav-text">User Documents</span>

                                </a>
                            </li> -->

                        </div>
                    </ul>

                </li>

                <li class="has-sub" id="static_pages_crud">
                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#static_pages" aria-expanded="true" aria-controls="static_pages">
                        <i class="mdi mdi-file-multiple"></i>
                        <span class="nav-text">{{tr('static_pages')}}</span> <b class="caret"></b>
                    </a>
                    <ul class="collapse" id="static_pages" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <li id="static_pages_create">
                                <a class="sidenav-item-link" href="{{route('admin.static_pages.create')}}">
                                    <span class="nav-text">{{tr('add_static_page')}}</span>

                                </a>
                            </li>

                            <li id="static_pages_view">
                                <a class="sidenav-item-link" href="{{route('admin.static_pages.index')}}">
                                    <span class="nav-text">{{tr('view_static_pages')}}</span>

                                </a>
                            </li>

                        </div>
                    </ul>

                </li>

                <li class="section-title">{{tr('setting_management')}}</li>

                <li id="settings">
                    <a class="sidenav-item-link" href="{{route('admin.settings')}}">
                        <i class="mdi mdi-settings"></i>
                        <span class="nav-text">{{tr('settings')}}</span>
                    </a>
                </li>

                <li class="section-title">
                    {{tr('profile_management')}}
                </li>

                <li id="profile">
                    <a class="sidenav-item-link" href="{{route('admin.profile')}}">
                        <i class="mdi mdi-account"></i>
                        <span class="nav-text">{{tr('profile')}}</span>
                    </a>
                </li>

                <li>
                    <a class="sidenav-item-link" href="{{route('admin.logout')}}" data-toggle="modal" data-target="#logoutModel">
                        <i class="mdi mdi-logout"></i>
                        <span class="nav-text">{{tr('logout')}}</span>
                    </a>
                </li>
            </ul>

        </div>


    </div>
</aside>

<script type="text/javascript">
    // Target id == Page 
    @if(isset($main_page))
    $("#{{$main_page}}").addClass("active expand");
    $("#{{$main_page}}").find('.sidenav-item-link').click();
    @endif

    @if(isset($page))
    $("#{{$page}}").addClass("show");
    @endif

    @if(isset($sub_page))
    $("#{{$sub_page}}").addClass("active");
    @endif
</script>

resources/views/layouts/admin/styles.blade.php
  <!-- GOOGLE FONTS -->
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">

<link rel="shortcut icon" href="{{Setting::get('site_icon') ?? asset('favicon.png')}}">

<link href="{{asset('admin-assets/plugins/material/css/materialdesignicons.min.css')}}" rel="stylesheet" />

<link href="{{asset('admin-assets/plugins/simplebar/simplebar.css')}}" rel="stylesheet" />

<!-- PLUGINS CSS STYLE -->
<link href="{{asset('admin-assets/plugins/nprogress/nprogress.css')}}" rel="stylesheet" />


<link href="{{asset('admin-assets/plugins/DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css')}}" rel="stylesheet" />

<link href="{{asset('admin-assets/plugins/jvectormap/jquery-jvectormap-2.0.3.css')}}" rel="stylesheet" />

<link href="{{asset('admin-assets/plugins/daterangepicker/daterangepicker.css')}}" rel="stylesheet" />

<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">


<link href="{{asset('admin-assets/plugins/toaster/toastr.min.css')}}" rel="stylesheet" />

<!-- CSS for Demo -->
<link rel="stylesheet" href="{{asset('admin-assets/options/optionswitch.css')}}"/>

<link href="{{asset('admin-assets/css/select2.min.css')}}" rel="stylesheet" />

<!-- Custom CSS -->
<link id="main-css-href" rel="stylesheet" href="{{asset('admin-assets/css/style.css')}}" />