routes/admin.php
<?php


Route::group(['middleware' => 'web'], function() {
    
    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('unverifed_users','AdminController@unverified_users_index')->name('unverified_users.index');

        Route::get('users/document_verify_status', 'AdminController@document_verify_status')->name('users.document_verify_status');

        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::get('razorpay', 'AdminController@razorpay_settings_control')->name('razorpay_settings_control');

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // Documents CRUD operations

        Route::get('/kyc_documents/index', 'AdminController@kyc_documents_index')->name('kyc_documents.index');

        Route::get('/kyc_documents/create', 'AdminController@kyc_documents_create')->name('kyc_documents.create');

        Route::get('/kyc_documents/edit', 'AdminController@kyc_documents_edit')->name('kyc_documents.edit');

        Route::post('/kyc_documents/save', 'AdminController@kyc_documents_save')->name('kyc_documents.save');

        Route::get('/kyc_documents/view', 'AdminController@kyc_documents_view')->name('kyc_documents.view');

        Route::get('/kyc_documents/delete', 'AdminController@kyc_documents_delete')->name('kyc_documents.delete');

        Route::get('/kyc_documents/status', 'AdminController@kyc_documents_status')->name('kyc_documents.status');


        Route::get('wallets','AdminController@user_wallets_index')->name('user_wallets.index');

        Route::get('wallets/view','AdminController@user_wallets_view')->name('user_wallets.view');

        Route::get('wallets/payments','AdminController@user_wallet_payments')->name('user_wallet_payments.index');

        Route::get('wallets/payments/view','AdminController@user_wallet_payments_view')->name('user_wallet_payments.view');

        Route::get('wallets/payments/status','AdminController@user_wallet_payments_status')->name('user_wallet_payments.status');

        
        Route::get('user/documents/view/','AdminController@user_kyc_documents_view')->name('user_kyc_documents.view');

        Route::get('user/documents/view/','AdminController@user_kyc_documents_view')->name('user_kyc_documents.view');

        Route::get('generated_invoices','AdminController@generated_invoices_index')->name('generated_invoices.index');

        Route::get('generated_invoices/view', 'AdminController@generated_invoices_view')->name('generated_invoices.view');

        Route::get('generated_invoices/delete', 'AdminController@generated_invoices_delete')->name('generated_invoices.delete');

        Route::get('billing_accounts', 'AdminController@user_billing_accounts_index')->name('user_billing_accounts.index');

        Route::get('billing_accounts/create', 'AdminController@user_billing_accounts_create')->name('user_billing_accounts.create');


        Route::post('billing_accounts/save', 'AdminController@user_billing_accounts_save')->name('user_billing_accounts.save');

        Route::get('billing_accounts/view', 'AdminController@user_billing_accounts_view')->name('user_billing_accounts.view');

        Route::get('billing_accounts/edit', 'AdminController@user_billing_accounts_edit')->name('user_billing_accounts.edit');

        Route::get('billing_accounts/delete', 'AdminController@user_billing_accounts_delete')->name('user_billing_accounts.delete');

        Route::get('billing_accounts/status', 'AdminController@user_billing_accounts_status')->name('user_billing_accounts.status');

        Route::get('withdraw-requests','AdminController@user_withdrawals_index')->name('user_withdrawals.index');

        Route::get('withdraw-requests/view','AdminController@user_withdrawals_view')->name('user_withdrawals.view');

        Route::get('withdraw-requests/paynow', 'AdminController@user_withdrawals_paynow')->name('user_withdrawals.paynow');

        Route::get('withdraw-requests/decline', 'AdminController@user_withdrawals_decline')->name('user_withdrawals.decline');
        
        Route::get('resolution-center', 'AdminController@resolution_center_index')->name('resolution_center_index');

        Route::get('user_disputes', 'AdminController@user_disputes_index')->name('user_disputes.index');

        Route::get('user_disputes/view', 'AdminController@user_disputes_view')->name('user_disputes.view');

        Route::get('user_disputes/approve', 'AdminController@user_disputes_approve')->name('user_disputes.approve');

        Route::get('user_disputes/reject', 'AdminController@user_disputes_reject')->name('user_disputes.reject');

        Route::post('user_disputes/view', 'AdminController@user_disputes_message_save')->name('user_disputes.message_save');

        Route::post('inboxes/view', 'AdminController@inboxes_view')->name('inboxes.view');

       
        Route::post('/users/bulk_action', 'AdminController@users_bulk_action')->name('users.bulk_action');


    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

app/KycDocument.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class KycDocument extends Model
{
	protected $hidden = ['deleted_at', 'id', 'unique_id'];

	protected $appends = ['kyc_document_id', 'kyc_document_unique_id'];

    public function getKycDocumentIdAttribute() {

        return $this->id;
    }

    public function getKycDocumentUniqueIdAttribute() {

        return $this->unique_id;
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query;
    
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        return $query->where('kyc_documents.status', APPROVED);
    
    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {
            $model->attributes['unique_id'] = "KYC"."-".uniqid();
        });

        static::created(function($model) {

            $model->attributes['unique_id'] = "KYC"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

    }
}

resources/views/admin/kyc_documents/_form.blade.php
            <div class="card-body">

                @if(Setting::get('is_demo_control_enabled') == NO)

                <form class="forms-sample" action="{{ route('admin.kyc_documents.save') }}" method="POST" enctype="multipart/form-data" role="form">

                    @else

                    <form class="forms-sample" role="form">

                        @endif

                        @csrf

                        <div class="form-body">

                            <input type="hidden" name="kyc_document_id" id="kyc_document_id" value="{{$kyc_document_details->id}}">

                            <div class="row p-t-20">


                                <div class="form-group col-md-12">
                                    <label for="name">{{ tr('name') }} <span class="admin-required">*</span></label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="{{ tr('name') }}" value="{{ old('name') ?: $kyc_document_details->name}}" required>
                                </div>

                            </div>

                            <div class="row">
                            
                                <div class="form-group col-md-6">
                                <label for="name">{{ tr('upload_preview_image') }} <span class="admin-required">*</span></label>
                                <span class="file_input_format_css"> {{tr('upload_files')}}</span> 
                                <div class="input-group col-xs-12">

                                        <input type="file" name="picture" class="form-control file-upload-info" placeholder="{{tr('upload_preview_image')}}" accept="image/*">

                                        <div class="input-group-append">
                                            <button class="btn btn-info" type="button">{{tr('upload')}}</button>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="row">

                                <div class="form-group col-md-12">

                                    <label for="simpleMde">{{ tr('description') }}</label>

                                    <textarea class="form-control" id="description" name="description">{{ old('description') ?: $kyc_document_details->description}}</textarea>

                                </div>

                            </div>

                        </div>

                        <div class="form-actions">

                            @if(Setting::get('is_demo_control_enabled') == NO )

                            <button type="submit" class="btn btn-primary btn-pill pull-right"> <i class="fa fa-check"></i>{{tr('save')}}</button>

                            @else

                            <button type="button" class="btn btn-primary btn-pill pull-right"> <i class="fa fa-check"></i>{{tr('save')}}</button>

                            @endif

                            <button type="reset" class="btn reset-btn btn-pill">{{tr('reset')}}</button>

                        </div>

                    </form>

            </div>

       

resources/views/admin/kyc_documents/_search.blade.php
<div class="col-md-12 mb-2">

        <form class="col-sm-12 col-sm-offset-6 search_box_css" action="{{route('admin.kyc_documents.index')}}" method="GET" role="search">

            <div class="row input-group">
                <div class="col-md-4"></div>
                <div class="col-md-3">
                    <input type="text" class="form-control" name="search_key" placeholder="{{tr('document_search_placeholder')}}" value="{{Request::get('search_key')??''}}"> <span class="input-group-btn"></span>
                </div>

                <div class="col-md-2">

                    <select class="form-control" name="status">

                        <option value="">{{tr('select_status')}}</option>
                        <option value="{{APPROVED}}" @if(Request::get('status')== APPROVED && Request::get('status')!='') selected @endif>{{tr('approved')}}</option>
                        <option value="{{DECLINED}}" @if(Request::get('status')== DECLINED && Request::get('status')!='') selected @endif>{{tr('declined')}}</option>
                       

                    </select>
                </div>


                <button type="submit" class="btn btn-info">
                    <span class="glyphicon glyphicon-search"> {{tr('search')}}</span>
                </button> &nbsp;&nbsp;
                <a class="btn btn-danger" href="{{route('admin.kyc_documents.index')}}">{{tr('clear')}}</a>
            </div>

        </form>
</div>

resources/views/admin/kyc_documents/create.blade.php
@extends('layouts.admin') 

@section('title', tr('add_document'))

@section('breadcrumbs')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.kyc_documents.index') }}">{{tr('documents')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('add_document')}}</span>
    </li>
           
@endsection 

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('add_document')}}

            <a class="btn btn-white pull-right" href="{{route('admin.kyc_documents.index')}}">
                <i class="fa fa-eye"></i> {{tr('view_documents')}}
            </a>
        </h4>

    </div>

    @include('admin.kyc_documents._form')

</div>

@endsection

resources/views/admin/kyc_documents/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_document'))

@section('breadcrumb')
	
    <li class="breadcrumb-item"><a href="{{ route('admin.kyc_documents.index') }}">{{tr('documents')}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{ tr('edit_document') }}</span>
    </li>
           
@endsection 

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('edit_document')}}

            <a class="btn btn-white pull-right" href="{{route('admin.kyc_documents.index')}}">
                <i class="fa fa-eye"></i> {{tr('view_document')}}
            </a>
        </h4>

    </div>

    @include('admin.kyc_documents._form')

</div>

@endsection

resources/views/admin/kyc_documents/index.blade.php
@extends('layouts.admin')

@section('title', tr('documents'))

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{ route('admin.kyc_documents.index') }}">{{tr('documents')}}</a></li>

<li class="breadcrumb-item active" aria-current="page">
    <span>{{ tr('view_documents') }}</span>
</li>

@endsection

@section('content')

<div class="col-lg-12 grid-margin stretch-card">

    <div class="card">

        <div class="card-header bg-info">

            <h4 class="m-b-0 text-white">{{tr('user_documents')}}
            <button type="button" class="badge badge-square badge-outline-light" data-toggle="popover" data-content="{{tr('kyc_documents_note')}}">?</button>

                <a class="btn btn-white pull-right" href="{{route('admin.kyc_documents.create')}}">
                    <i class="fa fa-plus"></i> {{tr('add_document')}}
                </a>
            </h4>

        </div>

        <div class="card-body">

            @include('admin.kyc_documents._search')

            <div class="table-responsive">

                <table id="dataTable" class="table data-table">

                    <thead>
                        <tr>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('document_name')}}</th>
                            <th>{{tr('status')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach($kyc_documents as $i => $document_details)

                        <tr>
                            <td>{{$i+1}}</td>

                            <td>
                                <a href="{{route('admin.kyc_documents.view' , ['kyc_document_id' => $document_details->id] )}}"> {{$document_details->name}}
                                </a>
                            </td>

                            <td>
                                @if($document_details->status == APPROVED)

                                <span class="badge badge-outline-success">
                                    {{ tr('approved') }}
                                </span>

                                @else

                                <span class="badge badge-outline-danger">
                                    {{ tr('declined') }}
                                </span>

                                @endif
                            </td>

                            <td>

                                <div class="template-demo">

                                    <div class="dropdown">

                                        <button class="btn btn-outline-primary  dropdown-toggle btm-sm" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{tr('action')}}
                                        </button>

                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">

                                            <a class="dropdown-item" href="{{ route('admin.kyc_documents.view',['kyc_document_id' => $document_details->id]) }}">
                                                {{tr('view')}}
                                            </a>

                                            @if(Setting::get('is_demo_control_enabled') == NO)

                                            <a class="dropdown-item" href="{{ route('admin.kyc_documents.edit',['kyc_document_id' => $document_details->id]) }}">
                                                {{tr('edit')}}
                                            </a>

                                            <a class="dropdown-item" onclick="return confirm(&quot;{{tr('document_delete_confirmation' , $document_details->name)}}&quot;);" href="{{ route('admin.kyc_documents.delete',['kyc_document_id' => $document_details->id]) }}">
                                                {{ tr('delete') }}
                                            </a>

                                            @else

                                            <a class="dropdown-item text-muted" href="javascript:;">
                                                {{tr('edit')}}
                                            </a>

                                            <a class="dropdown-item text-muted" href="javascript:;">
                                                {{ tr('delete') }}
                                            </a>

                                            @endif

                                            <div class="dropdown-divider"></div>

                                            @if($document_details->status == APPROVED)

                                            <a class="dropdown-item" href="{{ route('admin.kyc_documents.status',['kyc_document_id' => $document_details->id]) }}" onclick="return confirm(&quot;{{ $document_details->name }}-{{tr('document_decline_confirmation' , $document_details->name)}}&quot;);">

                                                {{tr('decline')}}
                                            </a>

                                            @else

                                            <a class="dropdown-item" href="{{ route('admin.kyc_documents.status',['kyc_document_id' => $document_details->id]) }}">
                                                {{tr('approve')}}
                                            </a>

                                            @endif


                                        </div>

                                    </div>

                                </div>

                            </td>

                        </tr>

                        @endforeach

                    </tbody>

                </table>

            </div>

        </div>

    </div>

</div>

@endsection

resources/views/admin/kyc_documents/view.blade.php
@extends('layouts.admin')

@section('title', tr('view_document'))

@section('breadcrumb')

<li class="breadcrumb-item"><a href="{{route('admin.kyc_documents.index')}}">{{tr('documents')}}</a></li>
<li class="breadcrumb-item active" aria-current="page">
    <span>{{tr('view_document')}}</span>
</li>

@endsection

@section('content')

<div class="row">

    <div class="col-md-12">

        <!-- Card group -->
        <div class="card-group">

            <!-- Card -->
            <div class="card mb-4">

                <!-- Card image -->
                <div class="view overlay">
                    <img class="card-img-top" src="{{$kyc_document_details->picture}}">
                    <a href="#!">
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>

                <!-- Card content -->
                <div class="card-body">

                    <!-- Title -->
                    <h4 class="card-title">{{ tr('description') }}</h4>
                    <!-- Text -->
                    <p class="card-text">{{ $kyc_document_details->description }}</p>

                </div>
                <!-- Card content -->

            </div>
            <!-- Card -->

            <!-- Card -->
            <div class="card mb-4">

                <!-- Card content -->
                <div class="card-body">

                    <div class="custom-card">

                        <h5 class="card-title">{{tr('name')}}</h5>

                        <p class="card-text">{{$kyc_document_details->name}}</p>

                    </div>

                    <div class="custom-card">

                        <h5 class="card-title">{{tr('status')}}</h5>

                        <p class="card-text">

                            @if($kyc_document_details->status == APPROVED)

                            <span class="badge badge-success badge-md text-uppercase">{{tr('approved')}}</span>

                            @else

                            <span class="badge badge-danger badge-md text-uppercase">{{tr('pending')}}</span>

                            @endif

                        </p>

                    </div>

                    <div class="custom-card">

                        <h5 class="card-title">{{tr('updated_at')}}</h5>

                        <p class="card-text">{{ common_date($kyc_document_details->updated_at,Auth::guard('admin')->user()->timezone) }}</p>

                    </div>

                    <div class="custom-card">

                        <h5 class="card-title">{{tr('created_at')}}</h5>

                        <p class="card-text">{{ common_date($kyc_document_details->created_at,Auth::guard('admin')->user()->timezone) }}</p>

                    </div>

                </div>
                <!-- Card content -->

            </div>

            <!-- Card -->

            <!-- Card -->
            <div class="card mb-4">

                <!-- Card content -->
                <div class="card-body">

                    @if(Setting::get('is_demo_control_enabled') == NO)

                    <a href="{{ route('admin.kyc_documents.edit',['kyc_document_id' => $kyc_document_details->id] ) }}" class="btn btn-primary btn-block">
                        {{tr('edit')}}
                    </a>

                    <a onclick="return confirm(&quot;{{tr('document_delete_confirmation' , $kyc_document_details->name)}}&quot;);" href="{{ route('admin.kyc_documents.delete',['kyc_document_id' => $kyc_document_details->id] ) }}" class="btn btn-danger btn-block">
                        {{ tr('delete') }}
                    </a>

                    @else

                    <button class="btn btn-primary btn-block" disabled>{{ tr('edit') }}</button>

                    <button class="btn btn-warning btn-block" disabled>{{ tr('delete') }}</button>

                    @endif

                    @if($kyc_document_details->status == APPROVED)

                    <a class="btn btn-warning btn-block" href="{{ route('admin.kyc_documents.status',['kyc_document_id' => $kyc_document_details->id] ) }}" onclick="return confirm(&quot;{{ $kyc_document_details->name }}-{{tr('document_decline_confirmation' , $kyc_document_details->name)}}&quot;);">

                        {{tr('decline')}}
                    </a>

                    @else

                    <a class="btn btn-success btn-block" href="{{ route('admin.kyc_documents.status',['kyc_document_id' => $kyc_document_details->id] ) }}">
                        {{tr('approve')}}
                    </a>

                    @endif



                </div>
                <!-- Card content -->

            </div>
            <!-- Card -->

        </div>
        <!-- Card group -->

    </div>

</div>


@endsection